@extends('admin.layouts.app')
@section('title','Communications Control')
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<div class="row g-3 mb-3">
 <div class="col-lg-5"><div class="card p-3"><h6>Send Broadcast</h6><form method="POST" action="{{ route('admin.execution.broadcast.send') }}">@csrf<div class="mb-2"><input class="form-control form-control-sm" name="title" placeholder="Title" required></div><div class="mb-2"><input class="form-control form-control-sm" name="channel" placeholder="Channel (in_app/email)"></div><div class="mb-2"><textarea class="form-control form-control-sm" name="message" rows="4" placeholder="Message" required></textarea></div><button class="btn btn-sm btn-primary">Send Broadcast</button></form></div></div>
 <div class="col-lg-7"><div class="card p-0 overflow-auto"><div class="p-3 border-bottom"><h6 class="mb-0">Recent Broadcasts</h6></div><table class="table table-sm mb-0"><thead><tr><th>Title</th><th>Channel</th><th>Created</th></tr></thead><tbody>@forelse($broadcasts as $b)<tr><td>{{ $b->title }}</td><td>{{ $b->channel ?? 'in_app' }}</td><td>{{ \Illuminate\Support\Carbon::parse($b->created_at)->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-3">No broadcasts.</td></tr>@endforelse</tbody></table></div>{{ $broadcasts->links() }}</div>
</div>
<div class="row g-3"><div class="col-lg-7"><div class="card p-0 overflow-auto"><div class="p-3 border-bottom"><h6 class="mb-0">Templates</h6></div><table class="table table-sm mb-0"><thead><tr><th>Name</th><th>Subject</th><th>Updated</th></tr></thead><tbody>@forelse($templates as $t)<tr><td>{{ $t->name ?? $t->template_key ?? '-' }}</td><td>{{ $t->subject ?? '-' }}</td><td>{{ \Illuminate\Support\Carbon::parse($t->updated_at)->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-3">No templates.</td></tr>@endforelse</tbody></table></div>{{ $templates->links() }}</div><div class="col-lg-5"><div class="card p-0 overflow-auto"><div class="p-3 border-bottom"><h6 class="mb-0">Recent Email Logs</h6></div><table class="table table-sm mb-0"><thead><tr><th>To</th><th>Subject</th><th>Status</th></tr></thead><tbody>@forelse($emailLogs as $log)<tr><td>{{ $log->recipient ?? '-' }}</td><td>{{ $log->subject ?? '-' }}</td><td>{{ $log->status ?? '-' }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-3">No logs.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
