<?php

namespace App\Constants;

class StoreErrorCodes
{
    public const STORE_DISABLED = 'STORE_DISABLED';

    public const APP_VERSION_UNSUPPORTED = 'APP_VERSION_UNSUPPORTED';

    public const NOT_A_PEER = 'NOT_A_PEER';

    public const WALLET_FROZEN = 'WALLET_FROZEN';

    public const WALLET_CLOSED = 'WALLET_CLOSED';

    public const INSUFFICIENT_COINS = 'INSUFFICIENT_COINS';

    public const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';

    public const PRODUCT_INACTIVE = 'PRODUCT_INACTIVE';

    public const VARIANT_NOT_FOUND = 'VARIANT_NOT_FOUND';

    public const OUT_OF_STOCK = 'OUT_OF_STOCK';

    public const STOCK_CHANGED = 'STOCK_CHANGED';

    public const PRICE_CHANGED = 'PRICE_CHANGED';

    public const CART_EMPTY = 'CART_EMPTY';

    public const CART_INVALID = 'CART_INVALID';

    public const ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND';

    public const ADDRESS_NOT_SERVICEABLE = 'ADDRESS_NOT_SERVICEABLE';

    public const PICKUP_POINT_NOT_AVAILABLE = 'PICKUP_POINT_NOT_AVAILABLE';

    public const DELIVERY_MINIMUM_NOT_MET = 'DELIVERY_MINIMUM_NOT_MET';

    public const QUANTITY_LIMIT_EXCEEDED = 'QUANTITY_LIMIT_EXCEEDED';

    public const ELIGIBILITY_FAILED = 'ELIGIBILITY_FAILED';

    public const UNAUTHORIZED = 'UNAUTHORIZED';

    public const FORBIDDEN = 'FORBIDDEN';

    public const VALIDATION_ERROR = 'VALIDATION_ERROR';

    public const INTERNAL_ERROR = 'INTERNAL_ERROR';

    public const IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT';

    public const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';

    public const ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED';

    public const RETURN_WINDOW_EXPIRED = 'RETURN_WINDOW_EXPIRED';

    public const RETURN_NOT_ALLOWED = 'RETURN_NOT_ALLOWED';

    public const CUSTOMIZED_PRODUCT_NON_RETURNABLE = 'CUSTOMIZED_PRODUCT_NON_RETURNABLE';

    public const RETURN_ALREADY_REQUESTED = 'RETURN_ALREADY_REQUESTED';

    public const REFUND_ALREADY_COMPLETED = 'REFUND_ALREADY_COMPLETED';

    public const MEMBERSHIP_LIMIT_EXCEEDED = 'MEMBERSHIP_LIMIT_EXCEEDED';

    public const OTP_REQUIRED = 'OTP_REQUIRED';

    public const OTP_INVALID = 'OTP_INVALID';

    public const OTP_EXPIRED = 'OTP_EXPIRED';

    public const MAKER_CHECKER_VIOLATION = 'MAKER_CHECKER_VIOLATION';
}
