<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #16213e; margin: 0; padding: 0; }
        .certificate { border: 8px solid #1d4ed8; padding: 44px; height: 680px; box-sizing: border-box; }
        .inner { border: 2px solid #93c5fd; height: 100%; padding: 42px; text-align: center; box-sizing: border-box; }
        .brand { font-size: 34px; font-weight: 700; letter-spacing: 1px; color: #0f172a; margin-bottom: 24px; }
        .title { font-size: 30px; font-weight: 700; color: #1d4ed8; margin-bottom: 32px; }
        .presented { font-size: 15px; color: #475569; margin-bottom: 12px; }
        .name { font-size: 42px; font-weight: 700; color: #111827; margin-bottom: 22px; }
        .details { width: 88%; margin: 24px auto 0; text-align: left; font-size: 15px; line-height: 1.8; }
        .details td:first-child { font-weight: 700; width: 42%; color: #334155; }
        .footer { margin-top: 34px; display: table; width: 100%; font-size: 13px; color: #475569; }
        .footer div { display: table-cell; width: 50%; }
    </style>
</head>
<body>
    @php
        $isLeadership = $submission->certification_type === \App\Models\CertificationSubmission::TYPE_LEADERSHIP;
        $title = $isLeadership ? 'Leadership Certification' : 'Entrepreneur Certification';
        $typeLabel = $isLeadership ? 'Leadership' : 'Entrepreneur';
    @endphp
    <div class="certificate">
        <div class="inner">
            <div class="brand">Peers Global Unity</div>
            <div class="title">{{ $title }}</div>
            <div class="presented">This certificate is proudly presented to</div>
            <div class="name">{{ $submission->full_name }}</div>
            <table class="details">
                <tr><td>Certification Type</td><td>{{ $typeLabel }}</td></tr>
                <tr><td>Business Name</td><td>{{ $submission->business_name ?: 'N/A' }}</td></tr>
                <tr><td>Certification Level</td><td>{{ $submission->certification_level ?: 'N/A' }}</td></tr>
                <tr><td>Score / Percentage</td><td>{{ (int) $submission->total_score }} / {{ (int) $submission->percentage }}%</td></tr>
                <tr><td>Certificate Number</td><td>{{ $submission->certificate_number }}</td></tr>
                <tr><td>Issued Date</td><td>{{ optional($submission->issued_at)->format('d M Y') }}</td></tr>
                <tr><td>Approved Date</td><td>{{ optional($submission->approved_at)->format('d M Y') }}</td></tr>
            </table>
            <div class="footer">
                <div>Generated by Peers Global Unity</div>
                <div style="text-align:right;">Authorized Certification</div>
            </div>
        </div>
    </div>
</body>
</html>
