<?php

return [
    'statuses' => [
        'free_trial_peer',
        'free_peer',
        'only_unity_peer',
        'Circle Peer',
        'Multi Circle Peer',
        'Charter Peer',
        'Industry Advisor',
        'Charter Investor',
        'Circle Founder',
        'Circle Director',
        'Board Advisor',
    ],

    'labels' => [
        'free_trial_peer' => 'Free Trial Peer',
        'free_peer' => 'Free Peer',
        'only_unity_peer' => 'Only Unity Peer',
        'circle_peer' => 'Circle Peer',
        'multi_circle_peer' => 'Multi Circle Peer',
        'charter_peer' => 'Charter Peer',
        'industry_advisor' => 'Industry Advisor',
        'charter_investor' => 'Charter Investor',
        'circle_founder' => 'Circle Founder',
        'circle_director' => 'Circle Director',
        'board_advisor' => 'Board Advisor',
        'Only Unity Peer' => 'Only Unity Peer',
        'Circle Peer' => 'Circle Peer',
        'Multi Circle Peer' => 'Multi Circle Peer',
        'Charter Peer' => 'Charter Peer',
        'Industry Advisor' => 'Industry Advisor',
        'Charter Investor' => 'Charter Investor',
        'Circle Founder' => 'Circle Founder',
        'Circle Director' => 'Circle Director',
        'Board Advisor' => 'Board Advisor',
    ],
];
